# Creating a logistic regression to predict absenteeism

## Import the relevant libraries

In [ ]:

import pandas as pd
import numpy as np

## Load the data

In [ ]:

data_preprocessed = pd.read_csv('/content/Absenteeism_preprocessed.csv')

In [ ]:

data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  
0               30          0         2    1                          4  
1               31          0         1    0                          0  
2               31          0         0    0                          2  
3               24          0         2    0                          4  
4               30          0         2    1                          2

## Create the targets

In [ ]:

data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [ ]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 3, 1, 0)

targets = np.where(data_preprocessed['Absenteeism Time in Hours'] >
                   data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)

In [ ]:

targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [ ]:

data_preprocessed['Excessive Absenteeism'] = targets

In [ ]:

data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  \
0               30          0         2    1                          4   
1               31          0         1    0                          0   
2               31          0         0    0                          2   
3               24          0         2    0                          4   
4               30          0         2    1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

## A comment on the targets

In [ ]:
targets.sum() / targets.shape[0]

0.45571428571428574

In [ ]:


data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours'],axis=1)

In [ ]:

data_with_targets is data_preprocessed

False

In [ ]:

data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Excessive Absenteeism  
0               30          0         2    1                      1  
1               31          0         1    0                      0  
2               31          0         0    0                      0  
3               24          0         2    0                      1  
4               30          0         2    1                      0

## Select the inputs for the regression

In [ ]:
data_with_targets.shape

(700, 15)

In [ ]:
data_with_targets.iloc[:,:14]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pet  
0                 30          0         2    1  
1                 31          0         1    0  
2                 31          0         0    0  
3                 24          0         2    0  
4                 30          0         2    1  
..               ...        ...       ...  ...  
695               22          1         2    0  
696               24          0         1    2  
697               25          1         0    0  
698               25          1         0    0  
699               25          0         1    1  

[700 rows x 14 columns]

In [ ]:
data_with_targets.iloc[:,:-1]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pet  
0                 30          0         2    1  
1                 31          0         1    0  
2                 31          0         0    0  
3                 24          0         2    0  
4                 30          0         2    1  
..               ...        ...       ...  ...  
695               22          1         2    0  
696               24          0         1    2  
697               25          1         0    0  
698               25          1         0    0  
699               25          0         1    1  

[700 rows x 14 columns]

In [ ]:

unscaled_inputs = data_with_targets.iloc[:,:-1]

## Standardize the data

In [ ]:

from sklearn.preprocessing import StandardScaler

absenteeism_scaler = StandardScaler()

In [ ]:

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

# create the Custom Scaler class
class CustomScaler(BaseEstimator, TransformerMixin):

    def __init__(self, columns, copy=True, with_mean=True, with_std=True):
        self.columns = columns
        self.copy = copy
        self.with_mean = with_mean
        self.with_std = with_std
        self.scaler = StandardScaler(copy=copy, with_mean=with_mean, with_std=with_std)
        self.mean_ = None
        self.var_ = None

    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self

    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.loc[:, ~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]


In [ ]:
# check what are all columns that we've got
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pet'], dtype=object)

In [ ]:

columns_to_scale = ['Month Value','Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Children', 'Pet']

# select the columns to omit
columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']

In [ ]:

columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [ ]:

absenteeism_scaler = CustomScaler(columns_to_scale)

In [ ]:
absenteeism_scaler.fit(unscaled_inputs)

CustomScaler(columns=['Month Value', 'Day of the Week',
                      'Transportation Expense', 'Distance to Work', 'Age',
                      'Daily Work Load Average', 'Body Mass Index', 'Children',
                      'Pet'])

In [ ]:

scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [ ]:
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1     0.030796        -0.800950   
1           0         0         0         0     0.030796        -0.800950   
2           0         0         0         1     0.030796        -0.232900   
3           1         0         0         0     0.030796         0.335149   
4           0         0         0         1     0.030796         0.335149   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0    -0.568019        -0.232900   
696         1         0         0         0    -0.568019        -0.232900   
697         1         0         0         0    -0.568019         0.335149   
698         0         0         0         1    -0.568019         0.335149   
699         0         0         0         1    -0.568019         0.335149   

     Transportation Expense  Distance to Work       Age  \
0                  1.005844          0.412816 -0.536062   
1                 -1.574681         -1.141882  2.130803   
2                 -0.654143          1.426749  0.248310   
3                  0.854936         -1.682647  0.405184   
4                  1.005844          0.412816 -0.536062   
..                      ...               ...       ...   
695               -0.654143         -0.533522  0.562059   
696                0.040034         -0.263140 -1.320435   
697                1.624567         -0.939096 -1.320435   
698                0.190942         -0.939096 -0.692937   
699                1.036026          0.074838  0.562059   

     Daily Work Load Average  Body Mass Index  Education  Children       Pet  
0                  -0.806331         0.767431          0  0.880469  0.268487  
1                  -0.806331         1.002633          0 -0.019280 -0.589690  
2                  -0.806331         1.002633          0 -0.919030 -0.589690  
3                  -0.806331        -0.643782          0  0.880469 -0.589690  
4                  -0.806331         0.767431          0  0.880469  0.268487  
..                       ...              ...        ...       ...       ...  
695                -0.853789        -1.114186          1  0.880469 -0.589690  
696                -0.853789        -0.643782          0 -0.019280  1.126663  
697                -0.853789        -0.408580          1 -0.919030 -0.589690  
698                -0.853789        -0.408580          1 -0.919030 -0.589690  
699                -0.853789        -0.408580          0 -0.019280  0.268487  

[700 rows x 14 columns]

In [ ]:
scaled_inputs.shape

(700, 14)

## Split the data into train & test and shuffle

### Import the relevant module

In [ ]:
from sklearn.model_selection import train_test_split

### Split

In [ ]:
train_test_split(scaled_inputs, targets)

[     Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
 516         0         0         0         1     0.929019        -0.800950   
 259         0         0         0         1     0.330204        -1.368999   
 661         0         1         0         0     0.929019         0.335149   
 224         1         0         0         0    -0.268611         0.903199   
 83          0         0         1         0     1.527833         0.903199   
 ..        ...       ...       ...       ...          ...              ...   
 216         0         0         0         0    -0.568019        -0.232900   
 121         0         0         0         1     1.228426        -0.800950   
 430         0         0         0         1     1.228426         2.039298   
 213         0         0         0         0     1.228426         1.471248   
 574         1         0         0         0     0.330204        -0.232900   
 
      Transportation Expense  Distance to Work       Age  \
 5

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, #train_size = 0.8,
                                                                            test_size = 0.2, random_state = 20)

In [ ]:
print (x_train.shape, y_train.shape)

(560, 14) (560,)


In [ ]:
print (x_test.shape, y_test.shape)

(140, 14) (140,)


## Logistic regression with sklearn

In [ ]:
from sklearn.linear_model import LogisticRegression

from sklearn import metrics

### Training the model

In [ ]:
reg = LogisticRegression()

In [ ]:
reg.fit(x_train,y_train)

LogisticRegression()

In [ ]:
reg.score(x_train,y_train)

0.7660714285714286

### Manually check the accuracy

In [ ]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [ ]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [ ]:
model_outputs == y_train

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True, False,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [ ]:
# find out in how many instances we predicted correctly
np.sum((model_outputs==y_train))

429

In [ ]:
model_outputs.shape[0]

560

In [ ]:
np.sum((model_outputs==y_train)) / model_outputs.shape[0]

0.7660714285714286

### Finding the intercept and coefficients

In [ ]:
reg.intercept_

array([-1.60991897])

In [ ]:
reg.coef_

array([[ 2.78809595,  0.92273475,  3.10358519,  0.81724476,  0.01379249,
        -0.07594179,  0.62737945, -0.02990801, -0.17344994, -0.02273184,
         0.2816181 , -0.27058935,  0.36063506, -0.27446609]])

In [ ]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pet'], dtype=object)

In [ ]:
# save the names of the columns in an ad-hoc variable
feature_name = unscaled_inputs.columns.values

In [ ]:

summary_table = pd.DataFrame (columns=['Feature name'], data = feature_name)

summary_table['Coefficient'] = np.transpose(reg.coef_)

summary_table

Feature name  Coefficient
0                  Reason_1     2.788096
1                  Reason_2     0.922735
2                  Reason_3     3.103585
3                  Reason_4     0.817245
4               Month Value     0.013792
5           Day of the Week    -0.075942
6    Transportation Expense     0.627379
7          Distance to Work    -0.029908
8                       Age    -0.173450
9   Daily Work Load Average    -0.022732
10          Body Mass Index     0.281618
11                Education    -0.270589
12                 Children     0.360635
13                      Pet    -0.274466

In [ ]:

summary_table.index = summary_table.index + 1


summary_table.loc[0] = ['Intercept', reg.intercept_[0]]

summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                 Intercept    -1.609919
1                  Reason_1     2.788096
2                  Reason_2     0.922735
3                  Reason_3     3.103585
4                  Reason_4     0.817245
5               Month Value     0.013792
6           Day of the Week    -0.075942
7    Transportation Expense     0.627379
8          Distance to Work    -0.029908
9                       Age    -0.173450
10  Daily Work Load Average    -0.022732
11          Body Mass Index     0.281618
12                Education    -0.270589
13                 Children     0.360635
14                      Pet    -0.274466

## Interpreting the coefficients

In [ ]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [ ]:
summary_table

Feature name  Coefficient  Odds_ratio
0                 Intercept    -1.609919    0.199904
1                  Reason_1     2.788096   16.250049
2                  Reason_2     0.922735    2.516162
3                  Reason_3     3.103585   22.277678
4                  Reason_4     0.817245    2.264253
5               Month Value     0.013792    1.013888
6           Day of the Week    -0.075942    0.926870
7    Transportation Expense     0.627379    1.872697
8          Distance to Work    -0.029908    0.970535
9                       Age    -0.173450    0.840759
10  Daily Work Load Average    -0.022732    0.977525
11          Body Mass Index     0.281618    1.325273
12                Education    -0.270589    0.762930
13                 Children     0.360635    1.434240
14                      Pet    -0.274466    0.759978

In [ ]:
summary_table.sort_values('Odds_ratio', ascending=False)

Feature name  Coefficient  Odds_ratio
3                  Reason_3     3.103585   22.277678
1                  Reason_1     2.788096   16.250049
2                  Reason_2     0.922735    2.516162
4                  Reason_4     0.817245    2.264253
7    Transportation Expense     0.627379    1.872697
13                 Children     0.360635    1.434240
11          Body Mass Index     0.281618    1.325273
5               Month Value     0.013792    1.013888
10  Daily Work Load Average    -0.022732    0.977525
8          Distance to Work    -0.029908    0.970535
6           Day of the Week    -0.075942    0.926870
9                       Age    -0.173450    0.840759
12                Education    -0.270589    0.762930
14                      Pet    -0.274466    0.759978
0                 Intercept    -1.609919    0.199904